# Generated by Django 4.2.1 on 2023-06-01 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(max_length=500)),
                ("price", models.FloatField()),
                ("discounted_price", models.FloatField()),
                ("category", models.CharField(max_length=200)),
                ("image", models.CharField(max_length=300)),
            ],
            options={
                "ordering": [
                    "image",
                    "category",
                    "title",
                    "description",
                    "price",
                    "discounted_price",
                ],
            },
        ),
    ]
