# Generated by Django 4.2.1 on 2023-06-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_rename_products_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("items", models.CharField(max_length=1000)),
                ("name", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("state", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=200)),
                ("zip", models.IntegerField(max_length=10)),
                ("address", models.CharField(max_length=200)),
            ],
            options={
                "ordering": [
                    "name",
                    "email",
                    "address",
                    "city",
                    "zip",
                    "state",
                    "items",
                ],
            },
        ),
    ]
