# Generated by Django 4.2.1 on 2023-06-02 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": [
                    "name",
                    "email",
                    "address",
                    "city",
                    "zipcode",
                    "state",
                    "items",
                ]
            },
        ),
        migrations.RenameField(
            model_name="order",
            old_name="zip",
            new_name="zipcode",
        ),
    ]
