# Generated by Django 4.2.1 on 2023-06-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_alter_order_options_rename_zip_order_zipcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="zipcode",
            field=models.IntegerField(),
        ),
    ]
